### ISSUE TITLE
[Bug]: Respeaker 2-Mic Pi HAT不适用新的内核

### ISSUE THREAD

**Issue by 3853824** [respeaker/seeed-voicecard#339]
### Describe the bug

我的树莓派4B在运行sudo ./install_arm64.sh安装驱动的时候总会提示
WARNING Your loaded kernel version is 6.1.21 
Not matching the updated version

6.1.21
Kernel was updated, but	new kernel was not loaded yet	
Please reboot your machine AND THEN run this script again

这表明内核不匹配，而我的系统内核版本是6.1.21-v8+

### Expected behavior

有什么可以解决的办法，我不希望去重装早期的系统来去适配，希望官方能更新这个bug

### Platform

型号：Raspberry Pi 4B
系统：[Raspbian OS 64bit ]   发布时间2023.5.03

**Comment by HinTak** [comment]
Use the v6.1 branch of https://github.com/HinTak/seeed-voicecard

**Comment by mingxxming** [comment]
Building module:
cleaning build area...
make -j4 KERNELRELEASE=6.1.21-v8+ -C /lib/modules/6.1.21-v8+/build M=/var/lib/dkms/seeed-voicecard/0.3/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.1.21-v8+ (aarch64)
Consult /var/lib/dkms/seeed-voicecard/0.3/build/make.log for more information.
.
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 6.1.21-v8+ /boot/kernel8.img

------------------------------
Deleting module version: 0.3
completely from the DKMS tree.
------------------------------
Done.

Creating symlink /var/lib/dkms/seeed-voicecard/0.3/source ->
                 /usr/src/seeed-voicecard-0.3

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=6.1.21-v8+ -C /lib/modules/6.1.21-v8+/build M=/var/lib/dkms/seeed-voicecard/0.3/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.1.21-v8+ (aarch64)
Consult /var/lib/dkms/seeed-voicecard/0.3/build/make.log for more information.
mkdir: cannot create directory ‘/etc/voicecard’: File exists
git init
Reinitialized existing Git repository in /etc/voicecard/.git/
git add --all
git commit -m "origin configures"
On branch master
nothing to commit, working tree clean
------------------------------------------------------
Please reboot your raspberry pi to apply all settings
Enjoy!
------------------------------------------------------
root@raspberrypi:/data/seeed-voicecard# ^C
root@raspberrypi:/data/seeed-voicecard# ^C
root@raspberrypi:/data/seeed-voicecard# cart ^C
root@raspberrypi:/data/seeed-voicecard# cat  /var/lib/dkms/seeed-voicecard/0.3/build/make.log
DKMS make.log for seeed-voicecard-0.3 for kernel 6.1.21-v8+ (aarch64)
Fri  8 Nov 18:48:00 GMT 2024
make: Entering directory '/root/linux-0afb5e98488aed7017b9bf321b575d0177feb7ed'
  CC [M]  /var/lib/dkms/seeed-voicecard/0.3/build/wm8960.o
  CC [M]  /var/lib/dkms/seeed-voicecard/0.3/build/ac108.o
  CC [M]  /var/lib/dkms/seeed-voicecard/0.3/build/ac101.o
  CC [M]  /var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.o
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:57:26: error: field ‘cpu_dai’ has incomplete type
   57 |   struct simple_util_dai cpu_dai;
      |                          ^~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:58:26: error: field ‘codec_dai’ has incomplete type
   58 |   struct simple_util_dai codec_dai;
      |                          ^~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:85:25: error: field ‘cpu_dai’ has incomplete type
   85 |  struct simple_util_dai cpu_dai;
      |                         ^~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:86:25: error: field ‘codec_dai’ has incomplete type
   86 |  struct simple_util_dai codec_dai;
      |                         ^~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: In function ‘seeed_voice_card_startup’:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:114:6: error: implicit declaration of function ‘snd_soc_rtd_to_cpu’; did you mean ‘asoc_rtd_to_cpu’? [-Werror=implicit-function-declaration]
  114 |  if (snd_soc_rtd_to_cpu(rtd, 0)->driver->playback.channels_min) {
      |      ^~~~~~~~~~~~~~~~~~
      |      asoc_rtd_to_cpu
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:114:32: error: invalid type argument of ‘->’ (have ‘int’)
  114 |  if (snd_soc_rtd_to_cpu(rtd, 0)->driver->playback.channels_min) {
      |                                ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:115:63: error: invalid type argument of ‘->’ (have ‘int’)
  115 |   priv->channels_playback_default = snd_soc_rtd_to_cpu(rtd, 0)->driver->playback.channels_min;
      |                                                               ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:117:32: error: invalid type argument of ‘->’ (have ‘int’)
  117 |  if (snd_soc_rtd_to_cpu(rtd, 0)->driver->capture.channels_min) {
      |                                ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:118:62: error: invalid type argument of ‘->’ (have ‘int’)
  118 |   priv->channels_capture_default = snd_soc_rtd_to_cpu(rtd, 0)->driver->capture.channels_min;
      |                                                              ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:120:28: error: invalid type argument of ‘->’ (have ‘int’)
  120 |  snd_soc_rtd_to_cpu(rtd, 0)->driver->playback.channels_min = priv->channels_playback_override;
      |                            ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:121:28: error: invalid type argument of ‘->’ (have ‘int’)
  121 |  snd_soc_rtd_to_cpu(rtd, 0)->driver->playback.channels_max = priv->channels_playback_override;
      |                            ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:122:28: error: invalid type argument of ‘->’ (have ‘int’)
  122 |  snd_soc_rtd_to_cpu(rtd, 0)->driver->capture.channels_min = priv->channels_capture_override;
      |                            ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:123:28: error: invalid type argument of ‘->’ (have ‘int’)
  123 |  snd_soc_rtd_to_cpu(rtd, 0)->driver->capture.channels_max = priv->channels_capture_override;
      |                            ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: In function ‘seeed_voice_card_shutdown’:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:135:28: error: invalid type argument of ‘->’ (have ‘int’)
  135 |  snd_soc_rtd_to_cpu(rtd, 0)->driver->playback.channels_min = priv->channels_playback_default;
      |                            ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:136:28: error: invalid type argument of ‘->’ (have ‘int’)
  136 |  snd_soc_rtd_to_cpu(rtd, 0)->driver->playback.channels_max = priv->channels_playback_default;
      |                            ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:137:28: error: invalid type argument of ‘->’ (have ‘int’)
  137 |  snd_soc_rtd_to_cpu(rtd, 0)->driver->capture.channels_min = priv->channels_capture_default;
      |                            ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:138:28: error: invalid type argument of ‘->’ (have ‘int’)
  138 |  snd_soc_rtd_to_cpu(rtd, 0)->driver->capture.channels_max = priv->channels_capture_default;
      |                            ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: In function ‘seeed_voice_card_hw_params’:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:149:34: error: implicit declaration of function ‘snd_soc_rtd_to_codec’; did you mean ‘asoc_rtd_to_codec’? [-Werror=implicit-function-declaration]
  149 |  struct snd_soc_dai *codec_dai = snd_soc_rtd_to_codec(rtd, 0);
      |                                  ^~~~~~~~~~~~~~~~~~~~
      |                                  asoc_rtd_to_codec
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:149:34: warning: initialization of ‘struct snd_soc_dai *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:150:32: warning: initialization of ‘struct snd_soc_dai *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  150 |  struct snd_soc_dai *cpu_dai = snd_soc_rtd_to_cpu(rtd, 0);
      |                                ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: In function ‘seeed_voice_card_trigger’:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:214:28: warning: initialization of ‘struct snd_soc_dai *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  214 |  struct snd_soc_dai *dai = snd_soc_rtd_to_codec(rtd, 0);
      |                            ^~~~~~~~~~~~~~~~~~~~
In file included from ./include/linux/device.h:15,
                 from /var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:19:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:223:6: error: ‘struct snd_soc_dai’ has no member named ‘stream’
  223 |   dai->stream[SNDRV_PCM_STREAM_PLAYBACK].active, dai->stream[SNDRV_PCM_STREAM_CAPTURE].active);
      |      ^~
./include/linux/dev_printk.h:129:34: note: in definition of macro ‘dev_printk’
  129 |   _dev_printk(level, dev, fmt, ##__VA_ARGS__);  \
      |                                  ^~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:221:2: note: in expansion of macro ‘dev_dbg’
  221 |  dev_dbg(rtd->card->dev, "%s() stream=%s  cmd=%d play:%d, capt:%d\n",
      |  ^~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:223:53: error: ‘struct snd_soc_dai’ has no member named ‘stream’
  223 |   dai->stream[SNDRV_PCM_STREAM_PLAYBACK].active, dai->stream[SNDRV_PCM_STREAM_CAPTURE].active);
      |                                                     ^~
./include/linux/dev_printk.h:129:34: note: in definition of macro ‘dev_printk’
  129 |   _dev_printk(level, dev, fmt, ##__VA_ARGS__);  \
      |                                  ^~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:221:2: note: in expansion of macro ‘dev_dbg’
  221 |  dev_dbg(rtd->card->dev, "%s() stream=%s  cmd=%d play:%d, capt:%d\n",
      |  ^~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:245:10: error: ‘struct snd_soc_dai’ has no member named ‘stream’
  245 |   if (dai->stream[SNDRV_PCM_STREAM_CAPTURE].active && substream->stream == SNDRV_PCM_STREAM_PLAYBACK) {
      |          ^~
In file included from ./include/linux/device.h:15,
                 from /var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:19:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:265:6: error: ‘struct snd_soc_dai’ has no member named ‘stream’
  265 |   dai->stream[SNDRV_PCM_STREAM_PLAYBACK].active, dai->stream[SNDRV_PCM_STREAM_CAPTURE].active, ret);
      |      ^~
./include/linux/dev_printk.h:129:34: note: in definition of macro ‘dev_printk’
  129 |   _dev_printk(level, dev, fmt, ##__VA_ARGS__);  \
      |                                  ^~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:263:2: note: in expansion of macro ‘dev_dbg’
  263 |  dev_dbg(rtd->card->dev, "%s() stream=%s  cmd=%d play:%d, capt:%d;finished %d\n",
      |  ^~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:265:53: error: ‘struct snd_soc_dai’ has no member named ‘stream’
  265 |   dai->stream[SNDRV_PCM_STREAM_PLAYBACK].active, dai->stream[SNDRV_PCM_STREAM_CAPTURE].active, ret);
      |                                                     ^~
./include/linux/dev_printk.h:129:34: note: in definition of macro ‘dev_printk’
  129 |   _dev_printk(level, dev, fmt, ##__VA_ARGS__);  \
      |                                  ^~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:263:2: note: in expansion of macro ‘dev_dbg’
  263 |  dev_dbg(rtd->card->dev, "%s() stream=%s  cmd=%d play:%d, capt:%d;finished %d\n",
      |  ^~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: In function ‘simple_util_parse_dai’:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:314:8: error: too many arguments to function ‘snd_soc_of_get_dai_name’
  314 |  ret = snd_soc_of_get_dai_name(node, &dlc->dai_name, 0);
      |        ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:26:
./include/sound/soc.h:1288:5: note: declared here
 1288 | int snd_soc_of_get_dai_name(struct device_node *of_node,
      |     ^~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: In function ‘simple_util_init_dai’:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:334:16: error: invalid use of undefined type ‘struct simple_util_dai’
  334 |  if (simple_dai->sysclk) {
      |                ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:335:50: error: invalid use of undefined type ‘struct simple_util_dai’
  335 |   ret = snd_soc_dai_set_sysclk(dai, 0, simple_dai->sysclk,
      |                                                  ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:336:21: error: invalid use of undefined type ‘struct simple_util_dai’
  336 |           simple_dai->clk_direction);
      |                     ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:343:16: error: invalid use of undefined type ‘struct simple_util_dai’
  343 |  if (simple_dai->slots) {
      |                ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:345:23: error: invalid use of undefined type ‘struct simple_util_dai’
  345 |             simple_dai->slots *
      |                       ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:346:23: error: invalid use of undefined type ‘struct simple_util_dai’
  346 |             simple_dai->slot_width);
      |                       ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: In function ‘seeed_voice_card_dai_init’:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:415:30: warning: initialization of ‘struct snd_soc_dai *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  415 |  struct snd_soc_dai *codec = snd_soc_rtd_to_codec(rtd, 0);
      |                              ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:416:28: warning: initialization of ‘struct snd_soc_dai *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  416 |  struct snd_soc_dai *cpu = snd_soc_rtd_to_cpu(rtd, 0);
      |                            ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: In function ‘seeed_voice_card_dai_link_of’:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:481:8: error: implicit declaration of function ‘simple_util_parse_daifmt’; did you mean ‘simple_util_parse_dai’? [-Werror=implicit-function-declaration]
  481 |  ret = simple_util_parse_daifmt(dev, node, codec,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~
      |        simple_util_parse_dai
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:509:47: error: invalid use of undefined type ‘struct simple_util_dai’
  509 |  ret = snd_soc_of_parse_tdm_slot(cpu, &cpu_dai->tx_slot_mask,
      |                                               ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:510:15: error: invalid use of undefined type ‘struct simple_util_dai’
  510 |       &cpu_dai->rx_slot_mask,
      |               ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:511:15: error: invalid use of undefined type ‘struct simple_util_dai’
  511 |       &cpu_dai->slots,
      |               ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:512:15: error: invalid use of undefined type ‘struct simple_util_dai’
  512 |       &cpu_dai->slot_width);
      |               ^~
In file included from ./include/linux/device.h:15,
                 from /var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:19:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:514:11: error: invalid use of undefined type ‘struct simple_util_dai’
  514 |    cpu_dai->slots, cpu_dai->slot_width,
      |           ^~
./include/linux/dev_printk.h:129:34: note: in definition of macro ‘dev_printk’
  129 |   _dev_printk(level, dev, fmt, ##__VA_ARGS__);  \
      |                                  ^~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:513:2: note: in expansion of macro ‘dev_dbg’
  513 |  dev_dbg(dev, "cpu_dai : slot,width,tx,rx = %d,%d,%d,%d\n",
      |  ^~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:514:27: error: invalid use of undefined type ‘struct simple_util_dai’
  514 |    cpu_dai->slots, cpu_dai->slot_width,
      |                           ^~
./include/linux/dev_printk.h:129:34: note: in definition of macro ‘dev_printk’
  129 |   _dev_printk(level, dev, fmt, ##__VA_ARGS__);  \
      |                                  ^~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:513:2: note: in expansion of macro ‘dev_dbg’
  513 |  dev_dbg(dev, "cpu_dai : slot,width,tx,rx = %d,%d,%d,%d\n",
      |  ^~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:515:11: error: invalid use of undefined type ‘struct simple_util_dai’
  515 |    cpu_dai->tx_slot_mask, cpu_dai->rx_slot_mask
      |           ^~
./include/linux/dev_printk.h:129:34: note: in definition of macro ‘dev_printk’
  129 |   _dev_printk(level, dev, fmt, ##__VA_ARGS__);  \
      |                                  ^~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:513:2: note: in expansion of macro ‘dev_dbg’
  513 |  dev_dbg(dev, "cpu_dai : slot,width,tx,rx = %d,%d,%d,%d\n",
      |  ^~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:515:34: error: invalid use of undefined type ‘struct simple_util_dai’
  515 |    cpu_dai->tx_slot_mask, cpu_dai->rx_slot_mask
      |                                  ^~
./include/linux/dev_printk.h:129:34: note: in definition of macro ‘dev_printk’
  129 |   _dev_printk(level, dev, fmt, ##__VA_ARGS__);  \
      |                                  ^~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:513:2: note: in expansion of macro ‘dev_dbg’
  513 |  dev_dbg(dev, "cpu_dai : slot,width,tx,rx = %d,%d,%d,%d\n",
      |  ^~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:520:51: error: invalid use of undefined type ‘struct simple_util_dai’
  520 |  ret = snd_soc_of_parse_tdm_slot(codec, &codec_dai->tx_slot_mask,
      |                                                   ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:521:17: error: invalid use of undefined type ‘struct simple_util_dai’
  521 |       &codec_dai->rx_slot_mask,
      |                 ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:522:17: error: invalid use of undefined type ‘struct simple_util_dai’
  522 |       &codec_dai->slots,
      |                 ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:523:17: error: invalid use of undefined type ‘struct simple_util_dai’
  523 |       &codec_dai->slot_width);
      |                 ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:36:3: error: implicit declaration of function ‘simple_util_parse_clk’; did you mean ‘simple_util_parse_cpu’? [-Werror=implicit-function-declaration]
   36 |   simple_util_parse_clk(dev, node, simple_dai, dai_link->cpus)
      |   ^~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:530:8: note: in expansion of macro ‘simple_util_parse_clk_cpu’
  530 |  ret = simple_util_parse_clk_cpu(dev, cpu, dai_link, cpu_dai);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:543:8: error: implicit declaration of function ‘simple_util_set_dailink_name’; did you mean ‘simple_util_init_dai_link_params’? [-Werror=implicit-function-declaration]
  543 |  ret = simple_util_set_dailink_name(dev, dai_link,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |        simple_util_init_dai_link_params
In file included from ./include/linux/device.h:15,
                 from ./include/linux/acpi.h:15,
                 from ./include/linux/i2c.h:13,
                 from /var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:21:
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c: In function ‘ac108_hw_params’:
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:656:7: error: ‘struct snd_soc_dai’ has no member named ‘stream’
  656 |    dai->stream[SNDRV_PCM_STREAM_PLAYBACK].active, dai->stream[SNDRV_PCM_STREAM_CAPTURE].active);
      |       ^~
./include/linux/dev_printk.h:129:34: note: in definition of macro ‘dev_printk’
  129 |   _dev_printk(level, dev, fmt, ##__VA_ARGS__);  \
      |                                  ^~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:654:2: note: in expansion of macro ‘dev_dbg’
  654 |  dev_dbg(dai->dev, "%s() stream=%s play:%d capt:%d +++\n", __func__,
      |  ^~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:656:54: error: ‘struct snd_soc_dai’ has no member named ‘stream’
  656 |    dai->stream[SNDRV_PCM_STREAM_PLAYBACK].active, dai->stream[SNDRV_PCM_STREAM_CAPTURE].active);
      |                                                      ^~
./include/linux/dev_printk.h:129:34: note: in definition of macro ‘dev_printk’
  129 |   _dev_printk(level, dev, fmt, ##__VA_ARGS__);  \
      |                                  ^~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:654:2: note: in expansion of macro ‘dev_dbg’
  654 |  dev_dbg(dai->dev, "%s() stream=%s play:%d capt:%d +++\n", __func__,
      |  ^~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:667:59: error: ‘struct snd_soc_dai’ has no member named ‘stream’
  667 |  if ((substream->stream == SNDRV_PCM_STREAM_CAPTURE && dai->stream[SNDRV_PCM_STREAM_PLAYBACK].active)
      |                                                           ^~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:668:60: error: ‘struct snd_soc_dai’ has no member named ‘stream’
  668 |   || (substream->stream == SNDRV_PCM_STREAM_PLAYBACK && dai->stream[SNDRV_PCM_STREAM_CAPTURE].active)) {
      |                                                            ^~
/var/lib/dkms/seeed-voicecard/0.3/build/wm8960.c:1408:14: error: initialization of ‘int (*)(struct i2c_client *, const struct i2c_device_id *)’ from incompatible pointer type ‘int (*)(struct i2c_client *)’ [-Werror=incompatible-pointer-types]
 1408 |  .probe =    wm8960_i2c_probe,
      |              ^~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/wm8960.c:1408:14: note: (near initialization for ‘wm8960_i2c_driver.probe’)
/var/lib/dkms/seeed-voicecard/0.3/build/ac101.c: In function ‘ac101_hw_params’:
/var/lib/dkms/seeed-voicecard/0.3/build/ac101.c:1083:17: error: ‘struct snd_soc_dai’ has no member named ‘stream’
 1083 |    if (codec_dai->stream[SNDRV_PCM_STREAM_CAPTURE].active && dmic_used && codec_aif1_fs[i].samp_rate == 44100) {
      |                 ^~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c: At top level:
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:1548:14: error: initialization of ‘int (*)(struct i2c_client *, const struct i2c_device_id *)’ from incompatible pointer type ‘int (*)(struct i2c_client *)’ [-Werror=incompatible-pointer-types]
 1548 |  .probe =    ac108_i2c_probe,
      |              ^~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:1548:14: note: (near initialization for ‘ac108_i2c_driver.probe’)
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:572:2: error: implicit declaration of function ‘simple_util_canonicalize_cpu’; did you mean ‘simple_util_parse_clk_cpu’? [-Werror=implicit-function-declaration]
  572 |  simple_util_canonicalize_cpu(dai_link->cpus, single_cpu);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |  simple_util_parse_clk_cpu
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:250: /var/lib/dkms/seeed-voicecard/0.3/build/ac101.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [scripts/Makefile.build:250: /var/lib/dkms/seeed-voicecard/0.3/build/ac108.o] Error 1
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:574:2: error: implicit declaration of function ‘simple_util_canonicalize_platform’; did you mean ‘asoc_simple_canonicalize_platform’? [-Werror=implicit-function-declaration]
  574 |  simple_util_canonicalize_platform(dai_link->platforms, dai_link->cpus);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |  asoc_simple_canonicalize_platform
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: In function ‘seeed_voice_card_parse_of’:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:673:8: error: implicit declaration of function ‘simple_util_parse_card_name’; did you mean ‘simple_util_parse_dai’? [-Werror=implicit-function-declaration]
  673 |  ret = simple_util_parse_card_name(&priv->snd_card, PREFIX);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |        simple_util_parse_dai
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: In function ‘seeed_voice_card_probe’:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:888:2: error: implicit declaration of function ‘simple_util_clean_reference’ [-Werror=implicit-function-declaration]
  888 |  simple_util_clean_reference(&priv->snd_card);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: At top level:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:918:12: error: initialization of ‘int (*)(struct platform_device *)’ from incompatible pointer type ‘void (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
  918 |  .remove = seeed_voice_card_remove,
      |            ^~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:918:12: note: (near initialization for ‘seeed_voice_card.remove’)
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:250: /var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.o] Error 1
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:250: /var/lib/dkms/seeed-voicecard/0.3/build/wm8960.o] Error 1
make: *** [Makefile:2012: /var/lib/dkms/seeed-voicecard/0.3/build] Error 2
make: Leaving directory '/root/linux-0afb5e98488aed7017b9bf321b575d0177feb7ed'

Still not working. 6.1.21-v8+

**Comment by HinTak** [comment]
Told you already, wrong branch.
Use the v6.1 branch of https://github.com/HinTak/seeed-voicecard

**Comment by mingxxming** [comment]
> Told you already, wrong branch. Use the v6.1 branch of https://github.com/HinTak/seeed-voicecard

It's v6.11 branch

root@raspberrypi:/data/seeed-voicecard# git branch
* v6.11
root@raspberrypi:/data/seeed-voicecard# git remote -v
origin  https://github.com/HinTak/seeed-voicecard.git (fetch)
origin  https://github.com/HinTak/seeed-voicecard.git (push)

**Comment by mingxxming** [comment]
Downgrade to 2023-12-05-raspios-bookworm-arm64 resloved.

> Told you already, wrong branch. Use the v6.1 branch of https://github.com/HinTak/seeed-voicecard

I  am foo.  It should be "v.6.1"  but not "v6.1x"

**Comment by dihan** [comment]
here is a little guide to help with the Pi 4 using HinTak's forked repo

https://github.com/dihan/pi-voice-assistant

**Comment by taurusnex** [comment]
> here is a little guide to help with the Pi 4 using HinTak's forked repo
> 
> https://github.com/dihan/pi-voice-assistant

this doesn't refer to the problem at all.
