### ISSUE TITLE
[Bug]: this and HINTAK not working on kernel 6.12.47

### ISSUE THREAD

**Issue by DaanNieuwenburg** [respeaker/seeed-voicecard#349]
### Describe the bug

This version is discontinued so tried HINTAK fork. default as version 6.6 and 6.14 return the following:
Error! Bad return status for module build on kernel: 6.12.47+rpt-rpi-v8 (aarch64)

log file of 6.14:

DKMS (dkms-3.2.0) make.log for seeed-voicecard/0.3 for kernel 6.12.47+rpt-rpi-v8 (aarch64)
Fri  3 Oct 13:27:19 BST 2025

Building module(s)
# command: make -j4 KERNELRELEASE=6.12.47+rpt-rpi-v8 -C /lib/modules/6.12.47+rpt-rpi-v8/build M=/var/lib/dkms/seeed-voicecard/0.3/build
make: Entering directory '/usr/src/linux-headers-6.12.47+rpt-rpi-v8'
  CC [M]  /var/lib/dkms/seeed-voicecard/0.3/build/wm8960.o
  CC [M]  /var/lib/dkms/seeed-voicecard/0.3/build/ac108.o
  CC [M]  /var/lib/dkms/seeed-voicecard/0.3/build/ac101.o
  CC [M]  /var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.o
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: In function ‘seeed_voice_card_startup’:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:103:46: error: ‘struct snd_soc_pcm_runtime’ has no member named ‘id’
  103 |                 seeed_priv_to_props(priv, rtd->id);
      |                                              ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:92:60: note: in definition of macro ‘seeed_priv_to_props’
   92 | #define seeed_priv_to_props(priv, i) ((priv)->dai_props + (i))
      |                                                            ^
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: In function ‘seeed_voice_card_shutdown’:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:133:46: error: ‘struct snd_soc_pcm_runtime’ has no member named ‘id’
  133 |                 seeed_priv_to_props(priv, rtd->id);
      |                                              ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:92:60: note: in definition of macro ‘seeed_priv_to_props’
   92 | #define seeed_priv_to_props(priv, i) ((priv)->dai_props + (i))
      |                                                            ^
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: In function ‘seeed_voice_card_hw_params’:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:153:46: error: ‘struct snd_soc_pcm_runtime’ has no member named ‘id’
  153 |                 seeed_priv_to_props(priv, rtd->id);
      |                                              ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:92:60: note: in definition of macro ‘seeed_priv_to_props’
   92 | #define seeed_priv_to_props(priv, i) ((priv)->dai_props + (i))
      |                                                            ^
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c: In function ‘seeed_voice_card_dai_init’:
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:418:46: error: ‘struct snd_soc_pcm_runtime’ has no member named ‘id’
  418 |                 seeed_priv_to_props(priv, rtd->id);
      |                                              ^~
/var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.c:92:60: note: in definition of macro ‘seeed_priv_to_props’
   92 | #define seeed_priv_to_props(priv, i) ((priv)->dai_props + (i))
      |                                                            ^
make[2]: *** [/usr/src/linux-headers-6.12.47+rpt-common-rpi/scripts/Makefile.build:249: /var/lib/dkms/seeed-voicecard/0.3/build/seeed-voicecard.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:173:5: warning: no previous prototype for ‘ac10x_read’ [-Wmissing-prototypes]
  173 | int ac10x_read(u8 reg, u8* rt_val, struct regmap* i2cm) {
      |     ^~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:184:5: warning: no previous prototype for ‘ac10x_write’ [-Wmissing-prototypes]
  184 | int ac10x_write(u8 reg, u8 val, struct regmap* i2cm) {
      |     ^~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:193:5: warning: no previous prototype for ‘ac10x_update_bits’ [-Wmissing-prototypes]
  193 | int ac10x_update_bits(u8 reg, u8 mask, u8 val, struct regmap* i2cm) {
      |     ^~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:1097:5: warning: no previous prototype for ‘ac108_audio_startup’ [-Wmissing-prototypes]
 1097 | int ac108_audio_startup(struct snd_pcm_substream *substream,
      |     ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:1109:6: warning: no previous prototype for ‘ac108_aif_shutdown’ [-Wmissing-prototypes]
 1109 | void ac108_aif_shutdown(struct snd_pcm_substream *substream,
      |      ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:1127:5: warning: no previous prototype for ‘ac108_aif_mute’ [-Wmissing-prototypes]
 1127 | int ac108_aif_mute(struct snd_soc_dai *dai, int mute, int direction) {
      |     ^~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:1271:5: warning: no previous prototype for ‘ac108_codec_remove’ [-Wmissing-prototypes]
 1271 | int ac108_codec_remove(struct snd_soc_codec *codec) {
      |     ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:1280:6: warning: no previous prototype for ‘ac108_codec_remove_void’ [-Wmissing-prototypes]
 1280 | void ac108_codec_remove_void(struct snd_soc_codec *codec) {
      |      ^~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:1286:5: warning: no previous prototype for ‘ac108_codec_suspend’ [-Wmissing-prototypes]
 1286 | int ac108_codec_suspend(struct snd_soc_codec *codec) {
      |     ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac108.c:1300:5: warning: no previous prototype for ‘ac108_codec_resume’ [-Wmissing-prototypes]
 1300 | int ac108_codec_resume(struct snd_soc_codec *codec) {
      |     ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac101.c:76:5: warning: no previous prototype for ‘ac101_read’ [-Wmissing-prototypes]
   76 | int ac101_read(struct snd_soc_codec *codec, unsigned reg) {
      |     ^~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac101.c:88:5: warning: no previous prototype for ‘ac101_write’ [-Wmissing-prototypes]
   88 | int ac101_write(struct snd_soc_codec *codec, unsigned reg, unsigned val) {
      |     ^~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac101.c:96:5: warning: no previous prototype for ‘ac101_update_bits’ [-Wmissing-prototypes]
   96 | int ac101_update_bits(struct snd_soc_codec *codec, unsigned reg,
      |     ^~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac101.c:449:6: warning: no previous prototype for ‘drc_config’ [-Wmissing-prototypes]
  449 | void drc_config(struct snd_soc_codec *codec)
      |      ^~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac101.c:496:6: warning: no previous prototype for ‘drc_enable’ [-Wmissing-prototypes]
  496 | void drc_enable(struct snd_soc_codec *codec,bool on)
      |      ^~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/ac101.c:526:6: warning: no previous prototype for ‘set_configuration’ [-Wmissing-prototypes]
  526 | void set_configuration(struct snd_soc_codec *codec)
      |      ^~~~~~~~~~~~~~~~~
make[1]: *** [/usr/src/linux-headers-6.12.47+rpt-common-rpi/Makefile:1970: /var/lib/dkms/seeed-voicecard/0.3/build] Error 2
make: *** [/usr/src/linux-headers-6.12.47+rpt-common-rpi/Makefile:236: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.12.47+rpt-rpi-v8'

# exit code: 2
# elapsed time: 00:00:05
----------------------------------------------------------------
 

### Expected behavior

.

### Platform

- Device: Raspberry Pi 4
- OS: Raspbian OS 64bit Desktop

### Relevant log output

```shell

```

**Comment by HinTak** [comment]
Use the correct branch. There is a separate branch for each minor kernel version on my fork. The default on mine is now v6.14 . You need the v6.12 branch to work again 6.12.47 kernel.

(Sorry I have been busy and there is no v6.15 branch yet, but that will be the default when I get to it)

**Comment by DaanNieuwenburg** [comment]
Thanks for the quick respons. I didn't know that the branch version was the kernel version. 
Seems to finally work now. Thank you very much
