### ISSUE TITLE
Error! Bad return status for module build on kernel: 4.14.30-v7+ (armv7l)

### ISSUE THREAD

**Issue by h21k** [respeaker/seeed-voicecard#53]
**arecord -l didn't show Respeaker 
then sudo ./install.sh 4mic resulted in:**

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=4.14.30+ -C /lib/modules/4.14.30+/build M=/var/lib/dkms/seeed-voicecard/0.3/build.....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.14.30+ (armv7l)
Consult /var/lib/dkms/seeed-voicecard/0.3/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=4.14.30-v7+ -C /lib/modules/4.14.30-v7+/build M=/var/lib/dkms/seeed-voicecard/0.3/build......(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.14.30-v7+ (armv7l)
Consult /var/lib/dkms/seeed-voicecard/0.3/build/make.log for more information.
------------------------------------------------------
Please reboot your raspberry pi to apply all settings
Enjoy!

**/var/lib/dkms/seeed-voicecard/0.3/build/make.log states:**

DKMS make.log for seeed-voicecard-0.3 for kernel 4.14.30-v7+ (armv7l)
Fri 30 Mar 01:13:50 BST 2018
make: Entering directory '/usr/src/linux-headers-4.14.30-v7+'
  AR      /var/lib/dkms/seeed-voicecard/0.3/build/built-in.o
  CC [M]  /var/lib/dkms/seeed-voicecard/0.3/build/wm8960.o
  CC [M]  /var/lib/dkms/seeed-voicecard/0.3/build/ac108.o
  CC [M]  /var/lib/dkms/seeed-voicecard/0.3/build/ac101.o
  CC [M]  /var/lib/dkms/seeed-voicecard/0.3/build/simple-card.o
/var/lib/dkms/seeed-voicecard/0.3/build/simple-card.c: In function ‘asoc_simple$
/var/lib/dkms/seeed-voicecard/0.3/build/simple-card.c:364:61: error: macro "aso$
  ret = asoc_simple_card_parse_clk_cpu(cpu, dai_link, cpu_dai);
                                                             ^
/var/lib/dkms/seeed-voicecard/0.3/build/simple-card.c:364:8: error: ‘asoc_simpl$
  ret = asoc_simple_card_parse_clk_cpu(cpu, dai_link, cpu_dai);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/seeed-voicecard/0.3/build/simple-card.c:364:8: note: each undecla$
/var/lib/dkms/seeed-voicecard/0.3/build/simple-card.c:368:67: error: macro "aso$
  ret = asoc_simple_card_parse_clk_codec(codec, dai_link, codec_dai);
                                                                   ^
/var/lib/dkms/seeed-voicecard/0.3/build/simple-card.c:368:8: error: ‘asoc_simpl$
  ret = asoc_simple_card_parse_clk_codec(codec, dai_link, codec_dai);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
scripts/Makefile.build:328: recipe for target '/var/lib/dkms/seeed-voicecard/0.$
make[1]: *** [/var/lib/dkms/seeed-voicecard/0.3/build/simple-card.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:1519: recipe for target '_module_/var/lib/dkms/seeed-voicecard/0.3/bui$
make: *** [_module_/var/lib/dkms/seeed-voicecard/0.3/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.14.30-v7+'

**Comment by Pillar1989** [comment]
Duplicate of #48
